### ISSUE TITLE
[Feature Request] Having binaries downloadable from releases page

### ISSUE THREAD

**Issue by matbgn** [acarl005/toerings#2]
I'm convinced that your project will have more traction if you propose directly some built binaries ready to be downloaded in the releases section.

It gives me the opportunity to ask you which architecture is it suited for? Will it only work on macOS or could we built it for Linux also?

In such case an AppImage will be wonderful 😄 OK yes I'm a Linux user 😋

**Comment by acarl005** [comment]
I just published a [release](https://github.com/acarl005/toerings/releases/tag/v0.0.0) with some binaries. Can you try it and let me know if it runs?

**Comment by matbgn** [comment]
Sooooo cool! AppImage works like a charm! Many thanks
